# Generated by Django 4.0.3 on 2022-03-06 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, default=None, null=True, upload_to='media/profile pictures')),
                ('address', models.TextField()),
                ('blood_type', models.CharField(max_length=50)),
                ('is_addictive', models.BooleanField()),
                ('national_id', models.IntegerField()),
                ('facebook', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('instagram', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('whatsapp', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('twitter', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
